# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25.0'

    - name: Sync workspace
      run: go work sync

    - name: Build
      run: |
        for mod in alert-engine ingestion-gateway log-agent query-api stream-processor tail-service store/kafka store/opensearch store/redis store/s3; do
          echo "Building $mod..."
          go build -v ./$mod/...
        done

    - name: Test
      run: |
        for mod in alert-engine ingestion-gateway log-agent query-api stream-processor tail-service store/kafka store/opensearch store/redis store/s3; do
          echo "Testing $mod..."
          go test -v ./$mod/...
        done
